# Source: daily 1‑minute JSON files in GCS
data_source: "json_gcs"
json_url_template: "https://storage.googleapis.com/garrettc-btc-bidspreadl20-data/archive/1min/{date}.json"

# Map your JSON keys -> internal names
field_map:
  timestamp: "time"
  price: "price"
  s20: "spread_avg_L20_pct"   # only L20 is present (that’s fine)

# Backtest window
start_date: "2025-08-07"
end_date:   "2025-09-02"

# Label horizon and cadence
horizon_sec: 300        # predict 5 minutes ahead
cadence_seconds: 60     # your JSON is 1-min resolution

# Features to consider (only s20 is required; others are optional if present)
use_depths: [20]        # set [5,20,50,100] later if you add them

# Output
write_indicator_csv: true

# (Optional metadata—used only for output file naming)
exchange: "kraken"
asset: "BTC"
